import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useRef, ChangeEvent } from 'react';

const Home: NextPage = () => {
  const [file, setFile] = useState<File | null>(null);
  const [fileUrl, setFileUrl] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [fileType, setFileType] = useState<string>('');
  const mediaRef = useRef<HTMLAudioElement | HTMLImageElement | HTMLVideoElement | null>(null);
  
  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      const selectedFile = files[0];
      setFile(selectedFile);
      setFileType(selectedFile.type);
      
      // Create a URL for the file preview
      const url = URL.createObjectURL(selectedFile);
      setFileUrl(url);
    }
  };
  
  const handleUpload = async () => {
    if (!file) return;
    
    setIsUploading(true);
    setUploadProgress(0);
    
    // Show upload progress
    const interval = setInterval(() => {
      setUploadProgress(prev => {
        if (prev >= 95) {
          clearInterval(interval);
          return 95;
        }
        return prev + 5;
      });
    }, 300);
    
    try {
      // Upload file to Pinata through our API route
      const formData = new FormData();
      formData.append('file', file);
      
      const response = await fetch('/api/files', {
        method: 'POST',
        body: formData,
      });
      
      if (!response.ok) {
        throw new Error('Upload failed');
      }
      
      // Get the Pinata URL from the response
      const pinataUrl = await response.text();
      
      clearInterval(interval);
      setUploadProgress(100);
      setFileUrl(pinataUrl); // Update the file URL to the Pinata URL
      alert('File uploaded successfully to IPFS via Pinata!');
    } catch (error) {
      console.error('Error uploading file:', error);
      alert('Failed to upload file');
    } finally {
      setIsUploading(false);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        
        <div className="mt-10 w-full max-w-md">
          <h2 className="text-2xl font-bold mb-4">IPFS File Upload with Pinata</h2>
          
          <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 mb-4 hover:border-blue-500 transition-colors">
            <input
              type="file"
              onChange={handleFileChange}
              className="hidden"
              id="file-upload"
              disabled={isUploading}
            />
            <label
              htmlFor="file-upload"
              className="flex flex-col items-center justify-center cursor-pointer"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-gray-400 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 11v6m0 0l-4-4m4 4l4-4m-4-7a9 9 0 00-9 9h18a9 9 0 00-9-9z" />
              </svg>
              <span className="text-sm text-gray-500">
                {file ? file.name : 'Select a file to upload'}
              </span>
              <span className="text-xs text-gray-400 mt-1">
                Upload any file to IPFS via Pinata
              </span>
            </label>
          </div>
          
          {fileUrl && (
            <div className="mb-4">
              <p className="text-sm font-medium mb-2">Preview:</p>
              {fileType.startsWith('image/') ? (
                <img 
                  src={fileUrl} 
                  alt="Uploaded file" 
                  className="w-full rounded-lg max-h-64 object-contain" 
                />
              ) : fileType.startsWith('audio/') ? (
                <audio
                  controls
                  src={fileUrl}
                  className="w-full"
                />
              ) : fileType.startsWith('video/') ? (
                <video
                  controls
                  src={fileUrl}
                  className="w-full max-h-64"
                />
              ) : (
                <div className="p-4 bg-gray-100 rounded-lg">
                  <p className="text-sm">File uploaded: <a href={fileUrl} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">{file?.name}</a></p>
                </div>
              )}
            </div>
          )}
          
          {isUploading ? (
            <div className="w-full">
              <div className="w-full bg-gray-200 rounded-full h-2.5">
                <div
                  className="bg-blue-600 h-2.5 rounded-full transition-all duration-300"
                  style={{ width: `${uploadProgress}%` }}
                ></div>
              </div>
              <p className="text-sm text-center mt-2">{uploadProgress}% Uploaded</p>
            </div>
          ) : (
            <button
              onClick={handleUpload}
              disabled={!file}
              className={`w-full py-2 px-4 rounded-md ${file ? 'bg-blue-600 hover:bg-blue-700 text-white' : 'bg-gray-300 text-gray-500 cursor-not-allowed'} transition-colors`}
            >
              Upload to IPFS
            </button>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
